[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/themes/dracula-default.toml",
  # "~/.config/alacritty/themes/catppuccin-frappe.toml",
  # "~/.config/alacritty/themes/one-dark.toml",
  # "~/.config/alacritty/themes/zenbones-forestbones-dark.toml",
  # "~/.config/alacritty/themes/zenbones-kanagawabones.toml",
  # "~/.config/alacritty/themes/zenbones-tokyobones-dark.toml",
  "~/.config/alacritty/themes/zenbones-duckbones.toml",
]

[window]
padding = { x = 8, y = 5 }
dynamic_padding = true
decorations = "None"
# opacity = 0.9
startup_mode = "Maximized"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 12
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking =  "Off" }
vi_mode_style = { shape = "Block", blinking =  "Off" }

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F2", action = "ToggleViMode" },
  { key = "P", mode = "Vi", action = "Paste" }
]

