# dracula, everforest_dark, focus_nova, varua, tokyonight-moon/storm
theme = "everforest_dark"

[editor]
mouse = false
cursorline = true
color-modes = true
shell = ["bash", "-ic"]
text-width = 120
rulers = [120]
trim-trailing-whitespace = true
#default-yank-register = "+"

[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["file-type", "separator", "spacer", "version-control"]
right = ["diagnostics", "selections", "register", "file-encoding", "file-line-ending", "position",  "position-percentage", "spacer"]
separator = "•"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.normal.space]
"." = ":config-reload"
w = ":w"
q = ":bc"

