# Need to declare language-server entries for some LSP providers for them to work, but not for others;
# e.g.: need to declare language-server entry for `deno-lsp` for it to work BUT not for the ones provided
# in `vscode-langservers-extracted` (`vscode-html/css-language-server`).
[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "ts"
] }
auto-format = false
language-servers = [ { name = "deno-lsp", except-features = ["format"] } ]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "js"
] }
auto-format = false
language-servers = [ { name = "deno-lsp", except-features = ["format"] } ]

[[language]]
name = "html"
file-types = ["html"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "html"
] }
auto-format = false
language-servers = [ { name = "vscode-html-language-server", except-features = [ "format" ] } ]

# Declaring a language-server entry for `vscode-css-language-server` or
# a separate language entry for `scss` turns off the language server for it for some reason;
# both the vscode LSP and deno's formatter work fine for `scss` with this setup even though
# `hx --health scss` shows no formatter configured for it
[[language]]
name = "css"
file-types = ["css", "scss"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "css"
] }
auto-format = false
language-servers = [ { name = "vscode-css-language-server", except-features = [ "format" ] } ]

[[language]]
name = "json"
file-types = ["json"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "json"
] }
auto-format = false
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] } ]

[[language]]
name = "markdown"
file-types = ["md"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = [
  "fmt", "--config", "/home/andres/.config/deno/deno.json", "-", "--ext", "md"
] }
auto-format = false
language-servers = []

