[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
indent = { tab-width = 2, unit = "  " }
auto-format = false
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
indent = { tab-width = 2, unit = "  " }
auto-format = false
language-servers = ["deno-lsp"]

[[language]]
name = "html"
file-types = ["html"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "html" ] }
auto-format = false

[[language]]
name = "css"
file-types = ["css", "scss"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "deno", args = ["fmt", "-", "--ext", "css" ] }
auto-format = true

